### ISSUE TITLE
Document how to use the query function

### ISSUE THREAD

**Issue by geekscrapy** [TheHive-Project/Cortex4py#7]
Is someone able to send me in the right direction to learn more about how the query object is used to get a subset of analyzers, please?

My use case is getting a list of analyzers for dataType ip, domain etc. with a minimum or maximum tlp value. At the moment I have the following which gets analyzers of ip type:

        query = In('dataTypeList', ['ip'])

I tried something like the following to evaluate the max_tlp value within the configuration object, but that failed (I didn't expect it would work!):

        query = And(In('dataTypeList', ['ip']), Child('configuration', 'max_tlp==2'))

So how would I access and evaluate fields within the configuration fields of an analyzer?

TIA!

**Comment by nadouani** [comment]
Hello, the analyzer configuration is a not indexed field, so you unfortunately cannot search on it.

We cannot index nested fields that don't have a fixed structure, and since the analyzer configurations are different among analyzers, the `configuration` field is not indexed.

For your use case, you need to list all the analyzers available for the given datatypes, and then filter by TLP programatically.
